name: posts_app_clean_arch
description: posts app clean archeiteture
 The following line prevents the package from being accidentally published to

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
